Repository chaaard/CSI-API-Prod, pull requests merged in 2024-07, with the labels that each got.

#41 Origin/enhancement 240618
  CSI.Application/Services/AnalyticsService.cs
  CSI.Infrastructure/Data/AppDBContext.cs
Labels: bug, enhancement

#42 Payment Recon
  CSI.API/Controllers/AnalyticsController.cs
  CSI.API/Mapping/MappingProfile.cs
  CSI.Application/DTOs/AccountingAdjustmentDto.cs
  CSI.Application/DTOs/AccountingMatchDto.cs
  CSI.Application/DTOs/AccountingMatchPaymentDto.cs
  CSI.Application/DTOs/AccountingProoflistAdjustmentsDto.cs
  CSI.Application/DTOs/AnalyticsParamsDto.cs
  CSI.Application/DTOs/PortalParamsDto.cs
  CSI.Application/Interfaces/IAnalyticsService.cs
  CSI.Application/Services/AnalyticsService.cs
  CSI.Application/Services/ProofListService.cs
  CSI.Domain/Entities/AccountingAccountsPayment.cs
  CSI.Domain/Entities/AccountingAdjustments.cs
  CSI.Domain/Entities/AccountingAnalytics.cs
  CSI.Domain/Entities/AccountingMatch.cs
  CSI.Domain/Entities/AccountingMatchPayment.cs
  CSI.Domain/Entities/AccountingProofListPayment.cs
  CSI.Domain/Entities/AccountingProoflistAdjustments.cs
  CSI.Domain/Entities/AccountingStatus.cs
  CSI.Infrastructure/Data/AppDBContext.cs
Labels: bug, enhancement

#45 Origin/2024/07/09
  CSI.API/Controllers/MerchantController.cs
  CSI.API/Program.cs
  CSI.Application/Interfaces/IMerchantService.cs
  CSI.Application/Services/CategoryService.cs
  CSI.Application/Services/MerchantService.cs
  CSI.Domain/Entities/Merchant.cs
  CSI.Infrastructure/Data/AppDBContext.cs
Labels: bug, duplicate

#47 Csi api prod merchant
  CSI.API/.config/dotnet-tools.json
  CSI.Application/Services/AnalyticsService.cs
Labels: enhancement

#48 Merchant
  CSI.API/Controllers/MerchantController.cs
  CSI.Application/Interfaces/IMerchantService.cs
  CSI.Application/Services/CategoryService.cs
  CSI.Application/Services/MerchantService.cs
  CSI.Domain/Entities/Merchant.cs
Labels: bug, enhancement

#49 Uat enhancements 07092024
  CSI.API/Controllers/AnalyticsController.cs
  CSI.Application/DTOs/AccountingAdjustmentDto.cs
  CSI.Application/DTOs/AccountingMatchPaymentDto.cs
  CSI.Application/DTOs/AccountingProoflistAdjustmentsDto.cs
  CSI.Application/DTOs/AccountingProoflistDto.cs
  CSI.Application/Interfaces/IAnalyticsService.cs
  CSI.Application/Services/AnalyticsService.cs
  CSI.Application/Services/ProofListService.cs
  CSI.Domain/Entities/AccountingAdjustments.cs
  CSI.Domain/Entities/AccountingProofListPayment.cs
  CSI.Domain/Entities/AccountingProoflistAdjustments.cs
  CSI.Domain/Entities/Location.cs
  CSI.Domain/Entities/VarianceMMS.cs
Labels: bug, enhancement

#51 Csi api prod merchant
  CSI.API/Controllers/AdjustmentController.cs
  CSI.API/Controllers/AnalyticsController.cs
  CSI.Application/DTOs/AdjustmentParams.cs
  CSI.Application/DTOs/AnalyticsDto.cs
  CSI.Application/DTOs/GenerateUBRenewalDto.cs
  CSI.Application/DTOs/GenerateUBVoucherDto.cs
  CSI.Application/DTOs/InvoiceDto.cs
  CSI.Application/Interfaces/IAdjustmentService.cs
  CSI.Application/Interfaces/IAnalyticsService.cs
  CSI.Application/Services/AdjustmentService.cs
  CSI.Application/Services/AnalyticsService.cs
  CSI.Domain/Entities/AnalyticsRemarks.cs
  CSI.Domain/Entities/AnalyticsView.cs
  CSI.Domain/Entities/GenerateUBRenewal.cs
  CSI.Domain/Entities/GenerateUBVoucher.cs
  CSI.Infrastructure/Data/AppDBContext.cs
Labels: enhancement

#53 Csi api prod merchant
  CSI.Application/DTOs/GenerateUBRenewalDto.cs
  CSI.Application/Services/AnalyticsService.cs
  CSI.Domain/Entities/GenerateUBRenewal.cs
Labels: enhancement
